
drop table if exists TEMP_TAGS;
create table TEMP_TAGS
(
    CLIENT_ID INT,
    INSTALLATION_ID INT,
    VENDOR_ID INT,
    SYSTEM VARCHAR(64),
    SUBSYSTEM VARCHAR(64),
    TAGNAME VARCHAR(32),
    MSGTYPE VARCHAR(64),
    PRIORITY VARCHAR(16),
    DESCRIPTION VARCHAR(256),
    ALREADY_EXISTS int
    );

insert into TEMP_TAGS 
SELECT DISTINCT CLIENT_ID,
    INSTALLATION_ID,
    VENDOR_ID,
    SYSTEM,
    SUBSYSTEM,
    TAGNAME,
    MSGTYPE,
    PRIORITY,
    DESCRIPTION,
    0
from ALARM_DATA a;
 

UPDATE TEMP_TAGS t, ALARM_TYPE a
SET t.ALREADY_EXISTS=1  
where t.client_id = a.client_id 
and t.installation_id = a.installation_id 
and t.vendor_id = a.vendor_ID
and t.system = a.system
and t.subsystem = a.subsystem 
and t.tagname=a.tagname; 


delete from TEMP_TAGS where ALREADY_EXISTS<>0;

insert into ALARM_TYPE
SELECT 
    t.CLIENT_ID,
    t.INSTALLATION_ID,
    t.VENDOR_ID,
    t.SYSTEM,
    t.SUBSYSTEM,
    t.TAGNAME,
    t.MSGTYPE,     
    t.PRIORITY,
    t.DESCRIPTION,
    0,0,0,0,0,0,0,'',''
FROM
    TEMP_TAGS t;
   
    
drop table TEMP_TAGS;

UPDATE ALARM_TYPE SET FLAG_ID_PRIORITY=1 WHERE PRIORITY='Low' OR PRIORITY='LOW';
UPDATE ALARM_TYPE SET FLAG_ID_PRIORITY=2 WHERE PRIORITY='Medium' OR PRIORITY='MEDIUM';
UPDATE ALARM_TYPE SET FLAG_ID_PRIORITY=3 WHERE PRIORITY='HIGH' and VENDOR_ID =0;

UPDATE ALARM_TYPE SET FLAG_ID_PRIORITY=2 WHERE PRIORITY='High' and VENDOR_ID =1;
UPDATE ALARM_TYPE SET FLAG_ID_PRIORITY=3 WHERE PRIORITY='CRITICAL' and VENDOR_ID =1;
 
 
 
