CREATE TABLE ALARM_DATA_BAK (
    CLIENT_ID INT,
    INSTALLATION_ID INT,
    VENDOR_ID INT,
    FILE_ID INT,
    ALM_TIME DATETIME,
    ALM_ID VARCHAR(32),
    SOURCE_NODE VARCHAR(32),
    SYSTEM VARCHAR(64),
    SUBSYSTEM VARCHAR(64),
    TAGNAME VARCHAR(32),
    MSGTYPE VARCHAR(64),
    PRIORITY VARCHAR(16),
    ALM_STATUS VARCHAR(16),
    DESCRIPTION VARCHAR(256),
    FOREIGN KEY (CLIENT_ID)
        REFERENCES A4CLIENT (CLIENT_ID),
    FOREIGN KEY (CLIENT_ID,INSTALLATION_ID)
        REFERENCES INSTALLATION (CLIENT_ID,INSTALLATION_ID),
    FOREIGN KEY (CLIENT_ID,INSTALLATION_ID,VENDOR_ID)
        REFERENCES VENDOR (CLIENT_ID,INSTALLATION_ID,VENDOR_ID),
    FOREIGN KEY (FILE_ID)
        REFERENCES ALARM_FILE (FILE_ID)
);

insert into ALARM_DATA_BAK
SELECT a.CLIENT_ID,
    a.INSTALLATION_ID,
    a.VENDOR_ID,
    a.FILE_ID,
    a.ALM_TIME,
    a.ALM_ID,
    a.SOURCE_NODE,
    a.SYSTEM ,
    a.SUBSYSTEM,
    a.TAGNAME,
    a.MSGTYPE,
    a.PRIORITY,
    a.ALM_STATUS,
    a.DESCRIPTION
    from ALARM_DATA a
    where a.ALM_TIME < '2017-08-01';
    
delete from ALARM_DATA where ALM_TIME < '2017-08-01';